# version: '3.10'
# services:
#   app:
#     container_name: backend-container
#     restart: always
#     build: .
#     ports:
#      - "8000:8001"
#     depends_on:
#       - mongo
#   mongo:
#     container_name: mongo-backend
#     image: mongo
#     expose:
#       -"27017"
#     ports:
#       -"27017:27017"
#     volumes:
#       -app:database

# volumes:
#   backendDB: C:\